### ISSUE TITLE
rework sounds

### ISSUE THREAD

**Issue by daniel-wer** [philippotto/Tron3D#111]
- [ ] non-annoying engine sound
- [ ] royalty free soundtrack
- [ ] 3D sound
- [ ] item collection sound
- [ ] event sound (you just killed player x)
